"""Compress feature promo images AND generate tiny blur-up placeholders.

Outputs:
  - public/assets/features/<name>.{png,webp}  : optimized full-res variants
  - lib/blur-placeholders.ts                  : base64 data URIs for blur-up

Sources for feature images live in ~/Downloads/ (zh_2..4, en_2..4). Hero
backgrounds (background.png + background-light.png) are read from where
they already sit under public/assets/ so we don't have to keep a separate
copy around.
"""

from __future__ import annotations

import base64
from io import BytesIO
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
FEATURE_OUT_DIR = ROOT / "public" / "assets" / "features"
FEATURE_OUT_DIR.mkdir(parents=True, exist_ok=True)

DOWNLOADS = Path.home() / "Downloads"
FEATURE_NAMES = ["zh_2", "zh_3", "zh_4", "en_2", "en_3", "en_4"]

# Hero backgrounds are already in the repo — we just need to read them to
# bake a blur placeholder for each one.
HERO_BG_SOURCES = {
    "background": ROOT / "public" / "assets" / "background.png",
    "background-light": ROOT / "public" / "assets" / "background-light.png",
}


def fmt(n: float) -> str:
    for unit in ("B", "KB", "MB"):
        if n < 1024:
            return f"{n:.0f}{unit}" if unit == "B" else f"{n:.1f}{unit}"
        n /= 1024
    return f"{n:.1f}GB"


def open_rgb(path: Path) -> Image.Image:
    img = Image.open(path)
    if img.mode == "RGBA":
        # Drop alpha if it's fully opaque — RGB is meaningfully smaller.
        if img.getchannel("A").getextrema() == (255, 255):
            img = img.convert("RGB")
    return img


def make_placeholder(img: Image.Image, width: int = 32) -> str:
    """Tiny low-res WebP, base64 data URI, suitable for an inline CSS bg."""
    height = max(1, round(img.height * width / img.width))
    small = img.convert("RGB").resize((width, height), Image.LANCZOS)
    buf = BytesIO()
    small.save(buf, format="WebP", quality=40, method=6)
    encoded = base64.b64encode(buf.getvalue()).decode()
    return f"data:image/webp;base64,{encoded}"


def main() -> None:
    print(f"Feature output: {FEATURE_OUT_DIR}")
    placeholders: dict[str, str] = {}
    total_before = 0
    total_after = 0

    # Feature promo images: compress + generate placeholder.
    for name in FEATURE_NAMES:
        src = DOWNLOADS / f"{name}.png"
        if not src.exists():
            print(f"  {name}: SKIPPED (source not found at {src})")
            # Still attempt to read existing optimized copy for placeholder.
            existing = FEATURE_OUT_DIR / f"{name}.png"
            if existing.exists():
                placeholders[name] = make_placeholder(open_rgb(existing))
            continue
        before = src.stat().st_size
        total_before += before
        img = open_rgb(src)

        png_out = FEATURE_OUT_DIR / f"{name}.png"
        img.save(png_out, format="PNG", optimize=True)

        webp_out = FEATURE_OUT_DIR / f"{name}.webp"
        img.save(webp_out, format="WebP", lossless=True, quality=100, method=6)

        placeholders[name] = make_placeholder(img)

        png_size = png_out.stat().st_size
        webp_size = webp_out.stat().st_size
        total_after += min(png_size, webp_size)
        print(
            f"  {name}: {fmt(before)} -> png {fmt(png_size)} | webp {fmt(webp_size)} | "
            f"blur {len(placeholders[name])}B"
        )

    # Hero backgrounds: placeholder only.
    for name, path in HERO_BG_SOURCES.items():
        if not path.exists():
            print(f"  {name}: missing source at {path}")
            continue
        placeholders[name] = make_placeholder(open_rgb(path))
        print(f"  {name}: blur placeholder {len(placeholders[name])}B")

    # Emit a TypeScript module other code can import.
    out_ts = ROOT / "lib" / "blur-placeholders.ts"
    body = [
        "/* Auto-generated by scripts/compress-features.py — do not edit. */",
        "",
        "export const BLUR_PLACEHOLDERS: Record<string, string> = {",
    ]
    for name, uri in placeholders.items():
        body.append(f'  "{name}": "{uri}",')
    body.append("};")
    body.append("")
    out_ts.write_text("\n".join(body), encoding="utf-8")
    print(f"\nWrote {out_ts}")

    if total_before:
        print(f"Feature compression: {fmt(total_before)} -> {fmt(total_after)} (best fmt)")


if __name__ == "__main__":
    main()
